/** Owner-approved figures for the bank interview. Amounts are Thai baht. */
export const BUSINESS_NATURES = [
  [
    'animal_feed',
    'Animal Feed Distributor',
    2700000,
    300,
    8500,
    'ผู้จัดจำหน่ายอาหารสัตว์',
    '动物饲料经销商',
  ],
  [
    'household_products',
    'Household Product',
    1500000,
    2400,
    600,
    'ผลิตภัณฑ์ของใช้ในครัวเรือน',
    '家居用品',
  ],
  ['cleaning_products', 'Cleaning Product', 1500000, 2700, 500, 'ผลิตภัณฑ์ทำความสะอาด', '清洁用品'],
  ['pet_shop', 'Pet Shop', 1500000, 1800, 800, 'ร้านขายสินค้าสัตว์เลี้ยง', '宠物店'],
  [
    'hardware_industrial',
    'Hardware & Industrial Supplies',
    1800000,
    900,
    2500,
    'อุปกรณ์ฮาร์ดแวร์และอุตสาหกรรม',
    '五金及工业用品',
  ],
  [
    'baby_children',
    "Baby & Children's Products Retail & Wholesale",
    1500000,
    1200,
    1200,
    'ค้าปลีกและค้าส่งสินค้าเด็ก',
    '婴幼儿用品零售与批发',
  ],
  [
    'fashion_accessories',
    'Fashion Accessories Retail & Wholesale',
    1200000,
    1800,
    600,
    'ค้าปลีกและค้าส่งเครื่องประดับแฟชั่น',
    '时尚配饰零售与批发',
  ],
  [
    'beauty_products',
    'Beauty Products Trading',
    1500000,
    1800,
    800,
    'ค้าผลิตภัณฑ์ความงาม',
    '美容产品贸易',
  ],
  [
    'motorcycle_parts',
    'Motorcycle Parts Trading',
    1800000,
    900,
    2000,
    'ค้าอะไหล่รถจักรยานยนต์',
    '摩托车零件贸易',
  ],
  ['food_products', 'Food Products Trading', 2100000, 3900, 500, 'ค้าผลิตภัณฑ์อาหาร', '食品贸易'],
  ['seafood', 'Seafood Trading', 2700000, 900, 3000, 'ค้าอาหารทะเล', '海鲜贸易'],
  [
    'car_accessories',
    'Car Accessories Trading',
    1800000,
    900,
    2200,
    'ค้าอุปกรณ์ตกแต่งรถยนต์',
    '汽车配件贸易',
  ],
  ['cosmetics', 'Cosmetic Trading', 1500000, 1800, 700, 'ค้าเครื่องสำอาง', '化妆品贸易'],
  [
    'educational_toys',
    'Educational Toys Trading',
    1500000,
    1500,
    1000,
    'ค้าของเล่นเพื่อการศึกษา',
    '益智玩具贸易',
  ],
  [
    'stationery_office',
    'Stationery & Office Supplies Trading',
    1500000,
    2400,
    700,
    'ค้าเครื่องเขียนและอุปกรณ์สำนักงาน',
    '文具及办公用品贸易',
  ],
  ['it_house', 'IT House', 2400000, 600, 5200, 'ร้านสินค้าไอที', 'IT 产品商店'],
] as const;

export function businessNature(key: string | null | undefined) {
  return BUSINESS_NATURES.find((row) => row[0] === key) ?? null;
}
