import { FIXED_ANSWERS } from '@/lib/domain/standard-answers';
import { withCheckDigit } from '@/lib/domain/validation/juristic-id';
import type { RenderContext } from './context';

/**
 * A plainly fictional company for previews and tests: every fact a variant may name is present,
 * the address is a real place (Nong Yai, Phon Thong, Roi Et) with a few real siblings, and the
 * learner is the larger of two shareholders. It is never stored and never shown to a learner.
 */
export const SAMPLE_CONTEXT: RenderContext = {
  facts: {
    company_name_th: 'บริษัท ตัวอย่างการค้า จำกัด',
    company_name_en: 'SAMPLE TRADING CO., LTD.',
    juristic_id: withCheckDigit('010556900012'),
    registered_on: '2026-04-16',
    registered_capital: 2_000_000,
    directors: [
      { name_th: 'นางสาวสมหญิง ตัวอย่าง', name_en: 'Miss Somying Tuayang' },
      { name_th: 'นายสมชาย ตัวอย่าง', name_en: 'Mr. Somchai Tuayang' },
    ],
    signing_authority: 'กรรมการหนึ่งคนลงลายมือชื่อและประทับตราสำคัญของบริษัท',
    address: {
      full: 'เลขที่ 87 หมู่ที่ 9 ตำบลหนองใหญ่ อำเภอโพนทอง จังหวัดร้อยเอ็ด 45110',
      house_no: '87',
      moo: '9',
      road: null,
      subdistrict: 'หนองใหญ่',
      district: 'โพนทอง',
      province: 'ร้อยเอ็ด',
      postcode: '45110',
      province_id: 1,
      district_id: 1,
      subdistrict_id: 1,
      postcode_source: 'printed',
      status: 'resolved',
      issues: [],
    },
    shareholders: [
      { name: 'นางสาวสมหญิง ตัวอย่าง', nationality: 'ไทย', shares: 12_000, percent: null },
      { name: 'นายสมชาย ตัวอย่าง', nationality: 'ไทย', shares: 8_000, percent: null },
    ],
    total_shares: 20_000,
    nature_of_business: 'ค้าส่งและค้าปลีกเสื้อผ้าสตรี',
    products_services: 'ชุดเดรส เสื้อ และกระโปรงสตรี',
    business_purpose: 'จัดตั้งขึ้นเพื่อประกอบธุรกิจ ค้าส่งและค้าปลีกเสื้อผ้าสตรี',
    main_clients: 'ร้านค้าปลีกในประเทศ',
    client_origin: 'หน้าร้านและช่องทางออนไลน์',
    main_suppliers: 'โรงงานตัดเย็บในกรุงเทพมหานคร',
    business_address: 'เลขที่ 87 หมู่ที่ 9 ตำบลหนองใหญ่ อำเภอโพนทอง จังหวัดร้อยเอ็ด',
    monthly_revenue: 'ประมาณ 300,000 บาท',
    revenue_basis: 'ยอดขายประมาณ 30 รายการต่อเดือน เฉลี่ยรายการละ 10,000 บาท',
    average_transaction: 'ประมาณ 10,000 บาท',
    monthly_transactions: 'ประมาณ 30 รายการต่อเดือน',
    source_of_funds: FIXED_ANSWERS.source_of_funds,
    first_incoming_funds: FIXED_ANSWERS.first_incoming_funds,
    account_purpose: FIXED_ANSWERS.account_purpose,
    promptpay_qr_purpose: FIXED_ANSWERS.promptpay_qr_purpose,
    customer_examples: 'ร้านบุษบา ร้อยเอ็ด',
    customer_profile: 'ร้านค้าปลีกในประเทศ',
    transaction_details:
      'ลูกค้าชำระด้วยการโอนเงินผ่านธนาคารและ PromptPay / QR เฉลี่ยรายการละประมาณ 10,000 บาท',
    operations_started: true,
    has_existing_customers: true,
    has_completed_transactions: true,
    has_regular_suppliers: true,
    learner_is_shareholder: true,
    business_category: 'clothing_fashion',
    holder_name: 'นางสาวสมหญิง ตัวอย่าง',
    position: 'กรรมการผู้จัดการ',
    director_count: 2,
    shareholder_count: 2,
    my_shares: 12_000,
    my_share_percent: 60,
  },
  geo: {
    province: { id: 1, th: 'ร้อยเอ็ด', en: 'Roi Et' },
    district: { id: 1, th: 'โพนทอง', en: 'Phon Thong' },
    subdistrict: { id: 1, th: 'หนองใหญ่', en: 'Nong Yai' },
    provinces: [
      { id: 2, th: 'ขอนแก่น', en: 'Khon Kaen' },
      { id: 3, th: 'มหาสารคาม', en: 'Maha Sarakham' },
      { id: 4, th: 'กาฬสินธุ์', en: 'Kalasin' },
      { id: 5, th: 'ยโสธร', en: 'Yasothon' },
    ],
    districts: [
      { id: 2, th: 'เมืองร้อยเอ็ด', en: 'Mueang Roi Et' },
      { id: 3, th: 'เสลภูมิ', en: 'Selaphum' },
      { id: 4, th: 'สุวรรณภูมิ', en: 'Suwannaphum' },
      { id: 5, th: 'เกษตรวิสัย', en: 'Kaset Wisai' },
    ],
    subdistricts: [
      { id: 2, th: 'แวง', en: 'Waeng' },
      { id: 3, th: 'โคกกกม่วง', en: 'Khok Kok Muang' },
      { id: 4, th: 'นาอุดม', en: 'Na Udom' },
      { id: 5, th: 'สว่าง', en: 'Sawang' },
    ],
  },
  categories: [
    {
      key: 'clothing_fashion',
      th: 'ค้าเสื้อผ้าและเครื่องแต่งกาย',
      en: 'Clothing and fashion trading',
      zh: '服装与时尚贸易',
      active: true,
    },
    {
      key: 'restaurant_catering',
      th: 'ร้านอาหารและบริการจัดเลี้ยง',
      en: 'Restaurants and catering',
      zh: '餐饮与宴会服务',
      active: true,
    },
    {
      key: 'construction_contracting',
      th: 'รับเหมาก่อสร้างและตกแต่ง',
      en: 'Construction and fit-out contracting',
      zh: '建筑与装修承包',
      active: true,
    },
    {
      key: 'software_it_services',
      th: 'บริการซอฟต์แวร์และเทคโนโลยีสารสนเทศ',
      en: 'Software and IT services',
      zh: '软件与信息技术服务',
      active: true,
    },
    {
      key: 'logistics_transport',
      th: 'ขนส่งและโลจิสติกส์',
      en: 'Transport and logistics',
      zh: '运输与物流',
      active: true,
    },
    {
      key: 'retired_sample',
      th: 'หมวดที่เลิกใช้แล้ว',
      en: 'A retired category',
      zh: '已停用的类别',
      active: false,
    },
  ],
};
